name: test_flutter_1

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  animations: ^2.0.7
  google_fonts: any
  dio: any
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.18
  cached_network_image: any
  flutter_svg: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/